- name: Add worker to swarm
  docker_swarm:
    state: join
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['18.130.155.106']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ '18.130.155.106:2377' ]

