version: "3.8"
services:
  backend:
    image: springcommunity/spring-petclinic-rest
    networks:
      - petclinic-net
    ports: 
      - target: 9966
        published: 9966
        protocol: tcp
    deploy:
      replicas: 2

  frontend:
    image: jamalh8/spring-petclinic-angular:dev
    build: ./spring-petclinic-angular
    networks:
      - petclinic-net
    deploy:
      replicas: 2
    ports: 
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      - backend
networks:
  petclinic-net:


    
