all:
  children:
    manager:
      hosts:
        18.134.4.163:
    worker:
      hosts:
        13.40.116.175:
    nginx-lb:
      hosts:
        35.178.206.179:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/aws-key-london.pem'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
