all:
  children:
    manager:
      hosts:
        18.134.160.111:
    worker:
      hosts:
        35.178.190.19:
    nginx-lb:
      hosts:
        18.169.239.111:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/aws-key-london.pem'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
