all:
  children:
    manager:
      hosts:
        13.40.157.254:
    worker:
      hosts:
        13.40.118.14:
    nginx-lb:
      hosts:
        18.170.72.9:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/aws-key-london.pem'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
