all:
  children:
    manager:
      hosts:
        13.40.114.179:
    worker:
      hosts:
        13.40.51.97:
    nginx-lb:
      hosts:
        3.8.15.116:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/aws-key-london.pem'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
