- name: Add worker to swarm
  docker_swarm:
    state: join
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['13.40.118.95']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ '13.40.118.95:2377' ]

